env:
  global:
  # Docker Repository
  - REPO=fjudith/nexus
  # Compute docker tag
  - TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH} ; fi`
  - NGINX=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "nginx"; else echo ${TRAVIS_BRANCH}-nginx ; fi`
  # Retreive commit ID
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "BsJ6wbCV4PZPqRyZIGFdHMmbJhIzQgxyiqE8YIXQ5Z/l2Mu/TYuGxqgA/FCvQh76QV0NpA72ZAjbZ4obAgCF8zZAHnPL7BQZ6SpagTxjSgeycrp7ludN5cvofkb9Fm495VB+Tp9ufZ0L5YroQNVvQIv2lbqslwYn7SLRaAXFY0OsJgM/XThXQCDQUsSerOW5GmNkl3N+erFM5JDv+uXjB11VMfDiTC8NW+OgPEUPfK5p1NELMEmL0MNW5gI1UCVqdlxKXTvsADmvF21MIFCMDBT/q5gt2UakfoXQNZe63rpnNhRuoCxoqMUhjoW5YM65CT2QB7TLPQH+RcmSB+QzABqr0ob/TgzmCuzfuPbeR5M9KiRB9/Xfy36SdXCcKJRhKflkncfx5QT0otR/svig9CyLotIUouFcU/Fu1oOWUjVdYxKX6pnFNBeaZev1Iap4mb05CmBik9nSIExGOvLOoMGY9Vvua30P84VHed2velXReQGWG8hRUOX5R/Rb/174+RlXpzkzVoijct/Up3KJSdPceQlNVGk1tdBPr8btOFmVR4rUuUbgTJRoJSa1eV3OswlNxwDAH7U2LmlNBJHxYNrQN747072f7y+6zOLxcsMvrH617u+hiOkxsQxvAbatzxiNh87xbzEqPSJLl6KYe1oc8vkxCJEh0l2D97j6mtM="
  - secure: "SlST+ZfOA8CyBEez7GCwvtsS6ekCtTitbJ/JA2XXkABiUWM7Kh8dCluLeorJhzrOFPSLXmCpc3vKPztX/G7Klgs1bnZ5vxKsAg9N43zZKJQ8S7CWzNED03xgfcS7HdmgVEwRHqIBGOs3K5jK/BjnvdFqD5qkteKqTCS4oDIx1RelQQ98qY8GVnNTlzieHf43Zpx0Ld5WVK1GNp9TxFPOsNfxd9yA6E4Te/15cFx5cEuHo0reHlwUpmX/LSff0SVDfq53nNutg2EaMD1fxpVqND29jG57ycOq0a2JQ1VkYE8y3ULRDSI6/C6maN1jOrLZjsdkplhVAP1+b79sZZR8rhc5mVhS3xl3U/so2h342+gd+q8K78Af447x9N62UnzfOkIjEx6ROCEIcpotee+dEbzNiOUG83hFEzfS2UI66tGyN6EsC1GAmMrlJMdF4zYP0e5H5kuN5Fc6nPxeOGCQvrrmkipArFSXnUFSVYXmId8hUetEzAi6DV57RU/wOr30tw+AsyAkSrur8Eq5j5Nj20qvQeJ2ciJZW8MazU0b0/m51DGLCcHZRX+IevUya3KkValtDqVM4aL9/PEnVXtCfSamRIFeg85LAJXPZdin13nE1kZ+omREaY4Yl4mHjVsdZyWK1CxWCIv6YFAe5v5HO0kv+tOIei+uZJluH3te/t8="
  - secure: "n87L5PyZ1ixXgSbkHcGODj/xeENREMiVen9/3tz5k5644Jh/NZUSGgXZJ56F65An6LqKH4W3xhBSCXKo6oGZq0npUgKkLng32OhAo2Td3g+QxA+QtVjA+BKxiEosgyCvr56GczZ/EwrZIHlxdaA5E5p425e0gCym+xrng1426dgyrGTQyqV7mLAIAXvJmHmFJENDc+T8rjW0c8fJbVH8fzmlXY3SXfrPppVWorvAH9tdi8slQmtWaN3CPH5+uAuzctFql9wyd8Zig8P0zomiGtlsCWDjcWLCGUMG0kCvUDuRDanNWwszCAwykIngriHSvS2ayipfwTkattpB3NxX3HcQuCS1SCKPE5DTr2r5vYc85j8NJiLzFtw2HgLd6VAOcdZiAmW7j49cOOfTt3ZORMFYl+OVBjlQ4f/mVds09SG62PfNvfh17tkq9PpYNrJXlOpBL/M1CLhcP1yT8doLXp0Hc4TT+WGwbCbpdMksXXGHlNJnRM51FkpdHfeAZ1u2QCejAtvy8xT/rxnyxYDArap4PfG7kDfHVYW89HFebCI4JrGO/zKtiQuM8yvaGKHF505mlzokYXJAZCYVyfAd2iX6PVgyjNyDUjCHiikSr7Uh3jUHAYUp/vEahK/D/U2uC1ULGcWi+W1rJEIVUaBU+LsBtEK0pawfK0997o+x95g="

  
sudo: required
services:
  - docker


before_install:
  # nexus build
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker run -d --name 'nexus' $REPO:$COMMIT
  # Wait for nexus to start
  - sleep 20
  # Nginx build
  - docker build -f nginx/Dockerfile -t $REPO:$COMMIT-nginx nginx/
  - docker run -d --name 'nexus-nginx' --link nexus:nexus -p 32701:8080 $REPO:$COMMIT-nginx


script:
  # Wait for nexus to start
  - sleep 5
  - docker logs nexus
  - docker logs nexus-nginx
  # -i, --include – include protocol headers in the output (H/F)
  # -L, --follow – specify request  COMMAND (GET, PUT, DELETE…)  to use
  - docker run --rm --link nexus-nginx:nginx phusion/baseimage /bin/bash -c "curl -i -L http://nginx:80"


after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO:$COMMIT-nginx $REPO:$NGINX
  - docker tag $REPO:$COMMIT-nginx $REPO:travis-$TRAVIS_BUILD_NUMBER-nginx
  - docker tag $REPO:$COMMIT-nginx $REPO:$SLAVE
  - docker tag $REPO:$COMMIT-nginx $REPO:travis-$TRAVIS_BUILD_NUMBER-slave
- docker push $REPO