env:
  global:
  # Docker Repository
  - REPO=fjudith/nexus
  # Compute docker tag
  - TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH} ; fi`
  - NGINX=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "nginx"; else echo ${TRAVIS_BRANCH}-nginx ; fi`
  # Retreive commit ID
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "wv+D5jtTAFZJLNw/1aykANeoxMkgMCG2hncEc2HZsnm5hAsK02367N3Q5BDGT792rOPnOks8K8lVDj7O9VS2O//icaRq+prcaj799MJILk/Vub4DaxJ41lNbJvQiYPq1FbsgV7FrRuQ8zjXWTIGcVKMA9sKt2P/craTPwfs3w0WMScCsVvDpnvyuMMYgTwsOqMLJlXjp5sAL5iuhDZ5D3ZPPt2qDkrXizvC8ulT+BZ3Z2990We7q2+YfGX250lgnPedIlCwcO8IADf+pvwSKx3G9wZiIF8jdqWx1pANW19SzZy2w1TONPFK64fGn9kHBbh7zYbctsz7wCzYBt6v6wWG+kQnaA9C4vNS6JmP8wT5RqEEg71Hw0ouskpbP+vwu7PJyhdqSXp3kUByCmTigNeMQFKeUSOFdXDXJH6JO1wQsZZRjt10Yf3UEQxgVoO3RtNXl7L2dGtDQhPOXx1jb4HjEPNldTTYvQ4vu2/yEpMjnTQ6c98Sxwk0hgd4g5N6zeIw0uYt+ePTE31SeKHtkWLFXFjkUl+FqwZPupfmJd3HXzD2ai5BAFpB3YhujzowCA0QS3Di5aMVfQf9NyKl4kHp8PPng6W6DWDbiFlC0srPqJMPYqGYkTXM0c9DWEqebNlhzLM+wd4uZAtCG5ygbUHupaomaajH6hz1mvFAEHx0="
  - secure: "tlMRbEZsnBLqUX/fm1hiWrJiNuaoKFQInU+rlaD4QghiUPpsPrgOzBNnA9+2JEf+d4ruc9BHpj7MDrO0vQYc5WIPMqvWPbYi+zavZWzX2ePgnEWnz0gz/YPnK6BpWnXDm0np9M+5cSOhyOAVzR5gqifxUOqwpo5a9Y0CRw93iEJ9Cp3wpKivm9m5bfTR7d/qK2bjeT4vc9UxF9Pqulsbnqymx8InGiFAVOSdYxiYzQLJNZ9TEb4KS+JHsE59LFa6eG0kHhyPE44yImcdYq/h1+PLXffkAEC7JlJhQBc4j2QsF8fGc0bQ8pHQccFdnJdyTgFXvmSCc0y0nGnL46OwBWRb+ZMY7EQwRWit9mjnVjksP5YxMG5sunuQc1jvfCR6b6HISZN3rlq4uvKA+8LrL0n2OUiWMIkDnVDvzttoZk77PYhOhtq8IGgoaygSl19z0Z6b9RO8lG2j5+Y8JEM/OK5s3Gzqtvmvfm7rvC+61drtoYuPZMhTxCVn2AfguXac2EmphTJP68yrRZx5tK8b/9H57D1OU1CkaJenvmPjloZX5nlqTzHi8S92enPDGSpNYGUMkPRdkxU+5Vo0AwF0MmXcUCxFn4YMTozRiw2bFhKjW3J+/kp5niaEOMLj850xjfCY0K0Sbu2KV1Lg5hsBv1XY8JwFErulPhwVRGEbyHM="

  
sudo: required
services:
  - docker


before_install:
  # nexus build
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker run -d --name 'nexus' $REPO:$COMMIT
  # Wait for nexus to start
  - sleep 60
  # Nginx build
  - docker build -f nginx/Dockerfile -t $REPO:$COMMIT-nginx nginx/
  - docker run -d --name 'nexus-nginx' --link nexus:nexus -p 32701:8080 $REPO:$COMMIT-nginx


script:
  # Wait for nexus to start
  - sleep 5
  - docker logs nexus
  - docker logs nexus-nginx
  # -i, --include – include protocol headers in the output (H/F)
  # -L, --follow – specify request  COMMAND (GET, PUT, DELETE…)  to use
  - docker run --rm --link nexus-nginx:nginx phusion/baseimage /bin/bash -c "curl -ik -L http://nginx:80"


after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO:$COMMIT-nginx $REPO:$NGINX
  - docker tag $REPO:$COMMIT-nginx $REPO:travis-$TRAVIS_BUILD_NUMBER-nginx
  - docker push $REPO